CC=gcc

socketcomplie: Server/server1_1.c Client/client1_1.c Server/server1_2.c Client/client1_2.c
	$(CC) Server/server1_1.c -o server1_1
	$(CC) Client/client1_1.c -o client1_1
	$(CC) Server/server1_2.c -o server1_2
	$(CC) Client/client1_2.c -o client1_2
